### ISSUE TITLE
"Unable to create a system terminal, creating a dumb terminal"

### ISSUE THREAD

**Issue by ghost** [chirs241097/jline4mcdsrv#1]
Once the server completes it's startup, I receive this message:

> Jul 08, 2020 2:04:58 AM org.jline.utils.Log logr 
> WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

Only the syntax highlighting appear to be functional and using debug logging as the warning suggests does nothing for me as I cannot run `debug start` until after this operation has already failed. If a higher level of debug logging exists, I am unaware of it and would greatly appreciate any documentation available.

I don't believe it to be a mod compatibility issue as this issue occurs on my fabric server that has other mods installed, in addition to the test server I installed only the latest fabric loader (0.6.1.45 for 1.16.1) and the latest version of this mod. I also run the server with the `nogui` flag as mentioned in the mods description.

The only thing I can think of that isn't standard is the fact that the server is inside a docker container using [itzg/mc-server](https://github.com/itzg/docker-minecraft-server). If one needed to recreate he enviroment in which I faced this issue, I created the docker container with the command `docker run -d -v ~/minecraft/server/mc-test:/data -it -e EULA=TRUE -e TYPE=FABRIC -p 25565:25565 --name mc-test itzg/minecraft-server --nogui` on Ubuntu Server 20.04 LTS.

**Comment by chirs241097** [comment]
I'm almost certain that this issue is unrelated to docker. This mod works fine in a Debian Buster image. It also works if the entrypoint script is replaced with one that just starts the server in the image you mentioned.

After some investigation, I think it's most likely associated with [the way they start the server](https://github.com/itzg/mc-server-runner/blob/7675731c4e9c9a98b9ffdfff1e2c4020c8f3df46/main.go#L81). JLine won't be able to access the tty if pipe is used to handle stdio, therefore it falls back to a dumb terminal. As a workaround you could try out other server images (I haven't got a recommendation because I don't use docker). I would also suggest you notify the image author of this potential issue.

Instead of a dumb terminal, I can also try creating a [virtual terminal](https://github.com/jline/jline3/wiki/Terminals#virtual-terminals) if the system terminal fails. However, that will probably impact the user experience (e.g. resizing may be broken).

Finally, I'm no expert on java, go or docker. Please correct me if I'm wrong.

**Comment by itzg** [comment]
@AlbyTheAlbatross if you pull the latest `itzg/minecraft-server` image I have added a new option that should fix the issue you were seeing:

https://github.com/itzg/docker-minecraft-server#interactive-and-color-console

**Comment by chirs241097** [comment]
Since we are now including JLine's terminal libraries, this should now work even without upstream fixes. Let me know if it doesn't.
