### ISSUE TITLE
watchdog crash when leaving the server in screen copy mode

### ISSUE THREAD

**Issue by Mari023** [chirs241097/jline4mcdsrv#21]
the server is running inside screen, when I left the server I may have left it in screen copy mode, which might have caused it to hang

when I came back and left copy mode, it displayed the crash, and exited minecraft and screen, which caused systemd to then restart the server
the ~1 day tick time lines up with when I last viewed the server console
crash report: https://gist.github.com/Mari023/519d86d4eb899bd0cc0325ca1d30bac9

---

when in copy mode, once screen fills it's buffer, writing to System.out will block, which will hang the server (and cause a watchdog crash)

**Comment by Fourmisain** [comment]
Hm... I'm not well versed in any of this, so I did some digging.

From what I gathered (e.g. in https://bugs.mojang.com/browse/MC-63590), the Server Watchdog thread kills the server if it lags for a too long time, which is what we can see in your log

> [20:58:09] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 119037387ms or 2380747 ticks behind
[20:58:09] [Server Watchdog/ERROR]: This crash report has been saved to: /home/minecraft/VanillaServer/./crash-reports/crash-2023-11-24_20.58.09-server.txt

So that makes perfect sense.
The time the watchdog considers "too high" is set by the `max-tick-time` server property and defaults to 60 seconds.
While increasing this or setting it to -1 would technically prevent the crash, it doesn't really fix anything since the real issue is the server freeze.

So why does it freeze?
I know that at least on Windows, marking the console output (aka entering copy mode) does freeze a lot of programs.

I just tried this with a vanilla server.
I let it load, marked the output, then tried joining with a client, but the connection timed out, which is already a bad sign.
After more than one minute of waiting, I unmarked the output and the server crashed / was terminated by the watchdog:

> [23:16:27] [Server Watchdog/ERROR] (net.minecraft.class_3178): A single server tick took 60.00 seconds (should be max 0.05)
[23:15:27] [Server thread/INFO] (net.minecraft.class_3248): Fourmisain (/127.0.0.1:53722) lost connection: Disconnected
[23:18:04] [Server Watchdog/ERROR] (net.minecraft.class_3178): Considering it to be crashed, server will forcibly shutdown.
[23:18:04] [Server thread/WARN] (net.minecraft.server.MinecraftServer): Can't keep up! Is the server overloaded? Running 156510ms or 3130 ticks behind

This is with vanilla, so I don't think this issue is related to jline or jline4mcdsrv at all.

Furthermore, I don't think this issue *can* even be fixed.
From my (poor) understanding, entering copy mode blocks any further output the process can do, so if it wants to print anything, like a "X joined the server" message, the process *has* to wait (is blocked) until copy mode is left.

I believe one workaround is to redirect the output to a file like `run_server_command >output.txt`
Out of curiosity I just tried this, and it does indeed work.
Copy mode does not block the server when there's not console output being done - makes sense, since there's simply nothing to block.
But it's obviously not a "solution" either.

So yeah, I don't think there is anything we can do to fix this.

**Comment by Mari023** [comment]
I know of the windows issue, but I am using windows

screen blocking on output could be an explanation, that would explain why I couldn't reproduce it - I didn't make the server print messages

tho I doubt that writing is blocking in screen, unless java / jline / jline4mcdsrv synchronously force a flush
tho even then, I don't think screen is supposed to block, ever

it isn't fixable by jline, then it probably is a screen bug, and it might be possible to be fixed there (that would however require me to reproduce it)

**Comment by Mari023** [comment]
I found a bug on the screen bug tracker which is probably the cause of this:
https://savannah.gnu.org/bugs/?63341
