### ISSUE TITLE
导致严重卡顿的问题

### ISSUE THREAD

**Issue by 0Lynk** [chirs241097/jline4mcdsrv#26]
问题描述：
当我在linux系统上长时间停留在minecraft后台时，这一mod可能导致了严重的服务器卡顿。

问题现象：
当我在游戏中持续生成一段时间区块且连接在SSH时，会产生严重的滞后和卡顿。
minecraft进程的TPS低至个位数，频发触发“Can't keep up!”警告。且服务器本身发生严重的卡顿，SFTP连接十分缓慢，SSH产生极大延迟。
关闭SSH链接后，卡顿立刻消失。

复现：
我仍然需要尝试如何复现问题，此问题偶尔会发生。

相关日志：
[2024-08-07-5.log](https://github.com/user-attachments/files/16531413/2024-08-07-5.log)

**Comment by Fourmisain** [comment]
(I used DeepL to translate your message. I'll try writing simple English.)

Hm... not sure what's going on, but here are some thoughts:

(1) There's a known issue https://github.com/chirs241097/jline4mcdsrv/issues/21 (and https://savannah.gnu.org/bugs/?63341) of remote connections (specifically using GNU `screen`) getting stuck in "copy mode", which blocks input/output and thus also the server itself.
This can result in huge lag spikes and even the watchdog killing the server.
Though from your description, there's still output happening, so maybe this is something else...?

(2) In jline4mcdsrv 0.6.0 I added a feature to restart the terminal on encountering an IOError.
This can theoretically loop endlessly, causing lag among other issues.
When it recovers, it should log a "restarted terminal due to IO error" message.
I'm not seeing that message your log, so it doesn't appear to be happening.
Maybe it's not a bad idea to try version 0.5.0 and see if that runs better.

(3) The log looks weird to me.
There's tons of DataFixerAPI logs like:
> [22:10:07] [ForkJoinPool.commonPool-worker-3/INFO] (Logger) [DataFixerAPI] Inspecting ./world/./dimensions/me/middle-earth/region/r.58.64.mca

Did you recently upgrade the server?
Try running
`java -jar fabric-server-launch.jar --forceUpgrade --eraseCache`
to upgrade all chunks/regions to the new version.

These are also weird, C2ME worked for almost 4 minutes(!) here:
> [22:16:56] [C2ME worker #2/INFO] (Minecraft) [Chunky] Task finished for edenring:edenring. Processed: 142129 chunks (100.00%), Total time: 0:03:50

There many Netty timeouts, which seems to imply the server is hanging completely:
> [22:20:35] [Netty Epoll Server IO #4/ERROR] (Minecraft) Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null

This one gives a hint:
> [23:03:21] [spark-worker-pool-1-thread-4/WARN] (spark) A command execution has not completed after 5 seconds, it *might* be stuck. Trace: 
  java.base/java.io.FileOutputStream.writeBytes(Native Method)
  java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
  org.jline.utils.FastBufferedOutputStream.flushBuffer(FastBufferedOutputStream.java:51)
  org.jline.utils.FastBufferedOutputStream.flush(FastBufferedOutputStream.java:58)
  java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:412)
  java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:214)
  java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:201)
  java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:262)
  java.base/java.io.PrintWriter.implFlush(PrintWriter.java:426)
  java.base/java.io.PrintWriter.flush(PrintWriter.java:418)
  org.jline.terminal.impl.AbstractTerminal.flush(AbstractTerminal.java:180)
  org.jline.utils.Display.update(Display.java:330)
  org.jline.utils.Display.update(Display.java:107)
  org.jline.reader.impl.LineReaderImpl.clear(LineReaderImpl.java:5926)
  org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3863)
  org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:903)
  org.chrisoft.jline4mcdsrv.JLineAppender.append(JLineAppender.java:34)

jline4mcdsrv tried to log something but got stuck outputting the bytes.
This sounds just like #21, so maybe that's it afterall?

> 当我在linux系统上长时间停留在minecraft后台时，这一mod可能导致了严重的服务器卡顿。

I'm not sure I understand, but do you put the server terminal into the background?
Maybe that prevents the terminal from being able to print, which will hang the IO operations and therefore the server itself.

If so, I don't think there's anything we can do about it, as this seems to be an issue/limitation with JLine, unfortunately.

Actually, I wonder if it is really an issue with JLine - did you try running the server without jline4mcdsrv?
Maybe putting the terminal with the SSH session in the background for a long time even hangs a vanilla server?

**Comment by 0Lynk** [comment]
Yes,it's sound like #21 
Today I try to recurrent this bug,but it didn‘t occur.
I will set watchdog at 60s and sustained attention the similar issues.
Once I get a crash-report for the same scenario, I'll upload it.

**Comment by 0Lynk** [comment]
我保留了问题发生时的spark报告，也许这会对定位问题有所帮助。
https://spark.lucko.me/EPdLFbLZB2

**Comment by 0Lynk** [comment]
为了防止spark网页过期，这是sparkprofile文件：
https://mega.nz/file/wiJTiDCK#tph8ihIHPnB8Ft0fhL3_3REWPtUnAeJzifd9YMi0Byk

**Comment by 0Lynk** [comment]
我的服务器存在于我内网中的另一台设备上，所以我使用MobaXterm通过SSH连接至服务器。我将minecraft进程运行在screen里面。
以上是对于提到的一些情况的回复：
（我并不精通英语，所以抱歉使用中文进行回复，我会尽量使用简单的词语）
（1）是的，这和提到的 #21 问题很像，但这里的情况更奇怪，产生了滞后，但并未彻底卡死终端，当每个滞后峰值结束时，终端仍然可以输出内容，甚至可以通过SFTP传输文件。
（3）不，服务器一直都是在同一版本下运行，从未进行过升级。netty超时的报告时有发生，但除了报告以外，并未导致过任何可见的网络问题。这一日志似乎发生在服务器发布网站询问服务器状态时。

**Comment by Fourmisain** [comment]
The spark profile seems confirm what we already suspect: the server tasks are getting hung up.
(`waitForTasks()` and `Unsafe.park()` go up from 39.68% to 94.48%, so it's just sitting there, waiting.)
Can't see any more than that.

> 我的服务器存在于我内网中的另一台设备上，所以我使用MobaXterm通过SSH连接至服务器。我将minecraft进程运行在screen里面。
以上是对于提到的一些情况的回复：
> (...)
>（1）是的，这和提到的 #21 问题很像，但这里的情况更奇怪，产生了滞后，但并未彻底卡死终端，当每个滞后峰值结束时，终端仍然可以输出内容，甚至可以通过SFTP传输文件。

Is your MobaXterm window/tab visible at all times?
I think if you hide the window or change the tab, it might cause the IO to pause and thus hang the server.

To be a more precise about what I think is happening:
The server often wants to log something to the console.
Everytime it wants to log, it needs to write a message, which will go through `screen`.
If the receiving end (MobaXterm) is currently not active, the server will wait until it is active again, no matter how long it will take.
When it gets stuck trying to log something, it cannot execute the actual game logic (on the same thread).
This is what you experience as server lag.

Maybe you can reproduce the issue like this:
 - switch the MobaXterm tab and hiding the window
 - connect with a Minecraft client
 - say something in chat (the server will try to log this and might start hanging)
 - say another thing in chat

If a chat message doesn't appear ingame, then you know the server is already stuck.

Maybe the issue disappears if you keep the MobaXterm server tab open and visible at all times, but I'm not sure.

I still wonder if this issue only happens with JLine, or if it happens with a vanilla server as well.
Can you maybe try running the server without jline4mcdsrv and see if the server still hangs?
If it does, then I think it's a system level issue that we can't fix.
If it only happens with JLine, maybe we can open an issue on their issue tracker and ask for help.

(I hope this is all legible, I tried to double check the translations with Google Translate as well.)

**Comment by 0Lynk** [comment]
我会尝试在没有jline4mcdsrv的情况下（甚至是原版服务器）复现这一问题，但我不确定能否成功再次复现它，这可能会需要很长时间。当我得以确认时将会再次向你报告。
